name = "stripe-cf-worker-backend"
main = "build/worker/shim.mjs"
compatibility_date = "2025-02-26"

[build]
command = "cargo install -q worker-build && worker-build --release"

[dev]
port = 4242
local_protocol = "http"
ip="192.168.2.6"